In [ ]:
import numpy as np

In [ ]:
1. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
import numpy as np
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
2. Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
import numpy as np
l = [1,2,0,0,4,0]
z = np.array(l)
l_new = list(np.nonzero(z)[0])
print(l_new)

[0, 1, 4]


In [ ]:
5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
import numpy as np 
z = np.random.random((10,10))
print(z)
zmin,zmax = z.min(),z.max()
print("minimum and maximum values:")
print(zmin,zmax)

[[0.13098752 0.0729095  0.41642737 0.72984958 0.82003508 0.32760482
  0.87241271 0.95071817 0.49023164 0.2242526 ]
 [0.30090328 0.85339407 0.24199227 0.16321257 0.46315946 0.21257122
  0.89915156 0.491866   0.78673407 0.72079526]
 [0.70295427 0.90039101 0.00886281 0.9953522  0.75968148 0.95019535
  0.59611821 0.31791036 0.55063086 0.88560854]
 [0.26016618 0.0900707  0.90690813 0.48701155 0.12264567 0.97884267
  0.12046588 0.57639499 0.52735918 0.0343537 ]
 [0.84924563 0.24255093 0.59578413 0.96059536 0.73184801 0.67223977
  0.27991806 0.61489927 0.21006633 0.89015829]
 [0.4993416  0.92808255 0.83696035 0.26308252 0.45209387 0.4785826
  0.73859744 0.76175627 0.12038088 0.28340132]
 [0.47707564 0.15469069 0.50081424 0.01362674 0.72661589 0.06104885
  0.43396826 0.1608276  0.91860613 0.59340772]
 [0.38067558 0.06054417 0.69972361 0.92400126 0.62229442 0.80369722
  0.76300414 0.95200044 0.71097159 0.26504675]
 [0.9290997  0.9370034  0.16590152 0.56062273 0.71317401 0.27635637
  0.64801674 

In [ ]:
6. Create a random vector of size 30 and find the mean value.

In [7]:
z = np.random.random(30)
m =z.mean()
print(m)

0.5004298550133207
